stash

diff --git a/assets/check b/assets/check
--- a/assets/check
+++ b/assets/check
@@ -8,51 +8,44 @@ exec 1>&2 # redirect all output to stderr for logging
 source /opt/resource/common.sh
 
 # Read inputs
+source=$1
 payload=$(mktemp $TMPDIR/helm-resource-request.XXXXXX)
 cat > $payload <&0
 
 # Prepare
-setup_resource $payload
+setup_resource $payload $source
 echo "Resource setup successful." 
-
 
 # Parse parameters
 namespace=$(jq -r '.source.namespace // "default"' < $payload)
-namespace_overwrite=$(jq -r '.params.namespace // ""' < $payload)
-current_namespace=$(jq -r '.version.namespace' < $payload || true)
+previous_namespace=$(jq -r '.version.namespace // "default"' < $payload || true)
 release=$(jq -r '.source.release // ""' < $payload)
-release_overwrite=$(jq -r '.params.release // ""' < $payload)
-current_release=$(jq -r '.version.release' < $payload || true)
-
-if [ -f "$source/$namespace_overwrite" ]; then
-  namespace=$(cat $source/$namespace_overwrite)
-elif [ -n "$namespace_overwrite" ]; then
-  namespace=$namespace_overwrite
-fi
+previous_release=$(jq -r '.version.release' < $payload || true)
+previous_revision=$(jq -r '.version.revision' < $payload || true)
 
 if [ -z "$namespace" ]; then
-  release="$current_namespace"
-fi
-
-if [ -f "$source/$release_overwrite" ]; then
-  release=$(cat $source/$release_overwrite)
-elif [ -n "$release_overwrite" ]; then
-  release=$release_overwrite
+  release="$previous_namespace"
 fi
 
 if [ -z "$release" ]; then
-  release="$current_release"
+  release="$previous_release"
 fi
 
 if [ "$release" ] ; then
-  revision=$($helm_bin history --max 20 --namespace $namespace $release 2>/dev/null | grep -i 'deployed' | awk '{print $1}' )
-  if [ "$revision" ] ; then
-    echo $revision | jq -R '.' | jq -s "map({\"revision\": ., \"release\": \"$release\"})" >&3
+  current_revision=$($helm_bin history --max 20 --namespace $namespace $release 2>/dev/null | grep -i 'deployed' | awk '{print $1}' )
+
+  if [ "$previous_revision" != "$current_revision" ] ; then
+    revision="$current_revision"
+  else
+    revision="$previous_revision"
+  fi
+  if [ "$revision" ]; then
+    echo $(jq -n "{version:{release:\"$release\", namespace:\"$namespace\", revision:\"$revision\"}}")
     exit 0
   fi
 fi
 
 # if we get here we couldnt find a revision to return so we bail - this is a good thing
 # since check should fail if its configuration cant point to a verifiable state.
-echo "Unable to confirm any revision for namspace: $namespace & release: $release" 
+echo "Unable to confirm any revision of release '$release' in  namspace: $namespace, does it exist yet?"
 exit 1
diff --git a/assets/out b/assets/out
--- a/assets/out
+++ b/assets/out
@@ -212,11 +212,6 @@ helm_upgrade() {
 }
 
 helm_delete() {
-  if [ -z "$release" ]; then
-    echo "invalid payload (missing release if delete=true)"
-    exit 1
-  fi
-
   echo "Deleting the release $release..."
   delete_args=("delete")
   if [ "$debug" = true ]; then
@@ -232,11 +227,6 @@ helm_delete() {
 }
 
 helm_test() {
-  if [ -z "$release" ]; then
-    echo "invalid payload (missing release if test=true)"
-    exit 1
-  fi
-  
   if [ "$debug" = true ]; then
     test_args+=("--debug")
   fi
@@ -255,12 +245,25 @@ helm_test() {
 }
 
 if [ "$delete" = true ]; then
+  if [ -z "$release" ]; then
+    echo "invalid payload (missing release if delete=true)"
+    exit 1
+  fi
+  deployed=$(current_deployed "$release")
+  revision=$(echo $deployed | awk '{print $1}')
   helm_delete
-  result="$(jq -n "{version:{release:\"$release\", deleted: \"true\"}, metadata: [{name: \"release\", value: \"$release\"}]}")"
+  result="$(jq -n "{version:{release:\"$release\", namespace:\"$namespace\", revision: \"$revision\"}, metadata: [{name: \"release\", value: \"$release\",{name: \"namespace\", value: \"$namespace\"},{name: \"revision\", value: \"$revision\"},{name:\"deleted\", value: \"true\"}]}")"
   echo "$result" | jq -s add  >&3
 elif [ "$test" = true ]; then
+  if [ -z "$release" ]; then
+    echo "invalid payload (missing release if test=true)"
+    exit 1
+  fi
+
+  deployed=$(current_deployed "$release")
+  revision=$(echo $deployed | awk '{print $1}')
   helm_test
-  result="$(jq -n "{version:{release:\"$release\", tested: \"true\"}, metadata: [{name: \"release\", value: \"$release\"}]}")"
+  result="$(jq -n "{version:{release:\"$release\", namespace:\"$namespace\", revision: \"$revision\"}, metadata: [{name: \"release\", value: \"$release\"},{name: \"namespace\", value: \"$namespace\"},{name: \"revision\", value: \"$revision\"},{name:\"tested\", value: \"true\"}]}")"
   echo "$result" | jq -s add  >&3
 else
   echo "Installing $release"
@@ -275,7 +278,7 @@ else
     revision=$(echo $deployed | awk '{ print $1 }')
     chart=$(echo $deployed | awk '{ print $8 }')
     echo "Deployed revision $revision of $release"
-    result="$(jq -n "{version:{release:\"$release\", revision:\"$revision\"}, metadata: [{name: \"release\", value: \"$release\"},{name: \"revision\", value: \"$revision\"},{name: \"chart\", value: \"$chart\"}]}")"
+    result="$(jq -n "{version:{release:\"$release\", namespace: \"$namespace\", revision:\"$revision\"}, metadata: [{name: \"release\", value: \"$release\"},{name: \"namespace\", value: \"$namespace\"},{name: \"revision\", value: \"$revision\"},{name: \"chart\", value: \"$chart\"}]}")"
     echo "$result" | jq -s add  >&3
   else
     echo "Debug was set to ${debug}; no release was performed. | tee $logfile"
